image:
  file: .gitpod/.gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: notify
    visibility: public

tasks:
  - name: 'Install'
    init: |
      nvm install
      nvm use
      npm ci
      gp sync-done installation

  - name: 'Serenity Reports'
    init: gp sync-await installation
    command: |
      mkdir -p target/site/serenity
      npx http-server -p 8080 target/site/serenity/

  - name: 'Welcome'
    init: gp sync-await installation
    command: |
      npm test
      echo "To view Serenity Reports, visit:"
      gp url 8080

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - EditorConfig.EditorConfig
    - CucumberOpen.cucumber-official

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
